services:
  git-livereload:
    build:
      context: ./git-livereload
    image: ${REGISTRY_URL:+${REGISTRY_URL}/}git-livereload:${IMAGE_TAG:-latest}
    volumes:
      - ${WINDSOR_PROJECT_ROOT-.}:/repos/mount/blueprint
