# This file is intended to be used only by the "blueprint template" repository.
# It is left here solely for reference purposes. If you wish, feel free to delete this file.
# Calls to these files should be made using the "uses" statement from the ci.yaml.

name: BLUEPRINT-CHECKS

on:
  workflow_call:

jobs:

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: '3.x'

      - name: Install yamllint
        run: pip install yamllint

      - name: Run yamllint
        run: yamllint .

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install ShellCheck
        run: sudo apt-get install -y shellcheck

      - name: Run ShellCheck
        run: |
          # Find all shell scripts and run shellcheck
          find . -name "*.sh" -print0 | xargs -0 shellcheck

  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run TrivyCheck
        run: |
          trivy fs --scanners vuln,secret,misconfig .
